## 1.创建数组

用 NumPy 创建一个长度为 10 的全 0 数组。

In [ ]:
import numpy as np
a = np.zeros((1,10),dtype = float)
print(a)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.93552348 0.79584583 0.44328236]
 [0.33638103 0.41795565 0.81638404]
 [0.24975464 0.48403744 0.50824142]]


In [9]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
a.shape = (2,3)
print(a)
print(a[0][1])

b = a.reshape(6,1)
print(b)


[[1 2 3]
 [4 5 6]]
2
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## 2.创建全1数组

创建一个 3×4 的全 1 矩阵。

In [ ]:
import numpy as np

a = np.ones((3,4),dtype = 'i4')
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


## 3.创建指定范围数组

生成 1 到 20 的等差数组（步长为 1）。

In [30]:
import numpy as np
a = np.arange(1,20,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [31]:
import numpy as np
a = np.eye(5)

print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 4.等差数列

生成 0 到 1 之间均匀分布的 5 个数。

In [33]:
import numpy as np
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


## 5.reshape

把数组 [1,2,3,4,5,6] 变成 2×3 矩阵。

In [41]:
import numpy as np
a =np.array([1,2,3,4,5,6]) 

b = a.reshape((2,3))
print(b)

[[1 2 3]
 [4 5 6]]


## 6.基本索引

给定矩阵：

[[1,2,3],
 [4,5,6],
 [7,8,9]]

取出第2行第3列元素。


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

b = a[1][2]
print(b)

6


## 7.切片

取出上述矩阵的前两行。

In [45]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

b = a[0:2]
print(b)

[[1 2 3]
 [4 5 6]]


## 8.列切片

取出矩阵的第2列。


In [49]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b = slice(0,2,2)
print(a[b])

[[1 2 3]]


## 9.条件筛选

生成数组 1~20，筛选出所有偶数。

In [51]:
a = np.arange(1, 21)
m = (a%2 == 0)
print(a[m])

[ 2  4  6  8 10 12 14 16 18 20]


## 10.替换元素

把数组中所有大于 10 的数改成 0。

In [53]:
a = np.arange(1, 21)
m = (a>10)
a[m] = 0
print(a)


[ 1  2  3  4  5  6  7  8  9 10  0  0  0  0  0  0  0  0  0  0]


## 11. 数组运算

创建两个 1~5 的数组，做加减乘除。

In [ ]:
a = np.arange(1,6)
b = np.arange(1,6)
print(np.add(a,b))      # a+b
print(np.subtract(a,b))     # a-b
print(np.multiply(a,b))     # a*b
print(np.divide(a,b))       # a/b

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]


## 12. 广播机制

把一个 3×3 矩阵 + 一个长度为 3 的数组。

In [63]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b = [1,2,3]
print(a+b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [68]:
a = np.array([
    [[1],[2]],
    [[3],[4]]
])
print(a.shape)
b = np.array([2,3])
print(a+b)

(2, 2, 1)
[[[3 4]
  [4 5]]

 [[5 6]
  [6 7]]]


In [70]:
a = np.array([
    [
        [1],
        [2]
    ],
    [
        [3],
        [4]
    ]
])

b = np.array([0,1])
print(a+b)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


## 13.最大最小值

求数组的最大值、最小值。

In [135]:
a = np.array([1,2,3,4])
print(np.max(a))
print(np.min(a))

4
1


## 14.平均值

求一个随机数组的平均值。


In [84]:

a = np.random.randint(0,10,(4,4))
print(a)
print(np.max(a,axis = 0))
print(np.average(a))

[[7 1 4 3]
 [5 0 3 2]
 [7 8 1 3]
 [8 1 5 7]]
[8 8 5 7]
4.0625


In [89]:
a = np.random.randint(0,10,(4,4))

print(a)
print(np.max(a))
print(np.max(a,axis = 0))
print(np.max(a,axis = 1))
print(np.min(a))
print(np.average(a,axis=1))

[[8 7 6 4]
 [3 4 7 6]
 [4 6 9 7]
 [1 5 5 6]]
9
[8 7 9 7]
[8 7 9 6]
1
[6.25 5.   6.5  4.25]


## 15.标准差

计算数组的标准差。

In [115]:
a = np.random.randint(0,10,(4,4))

print(np.std(a))

2.7271780286589284


## 16.矩阵乘法

计算两个矩阵的乘积（用 dot）。



In [117]:
a = np.random.randint(1,5,(2,3))
b = np.random.randint(1,5,(3,4))

result = np.dot(a,b)
print(a)
print(b)
print(result)

[[1 1 2]
 [4 1 1]]
[[4 4 4 4]
 [3 3 2 2]
 [2 2 4 3]]
[[11 11 14 12]
 [21 21 22 21]]


## 17.转置

对一个矩阵进行转置。


In [ ]:
a = np.random.randint(1,10,(2,3,4))
print(a)
print(a.shape)
print(a.T)
print(a.T.shape)


[[[8 1 8 2]
  [5 6 4 3]
  [7 6 4 3]]

 [[1 6 2 9]
  [5 5 1 4]
  [9 7 8 7]]]
(2, 3, 4)
[[[8 1]
  [5 5]
  [7 9]]

 [[1 6]
  [6 5]
  [6 7]]

 [[8 2]
  [4 1]
  [4 8]]

 [[2 9]
  [3 4]
  [3 7]]]
(4, 3, 2)
[[[8 1 8 2]
  [1 6 2 9]]

 [[5 6 4 3]
  [5 5 1 4]]

 [[7 6 4 3]
  [9 7 8 7]]]
(3, 2, 4)


In [138]:
a = np.random.randint(1,10,(2,3))
print(a)
b = np.left_shift(a,1)
print(b)
c = np.right_shift(a,1)
print(c)

[[9 1 7]
 [4 6 8]]
[[18  2 14]
 [ 8 12 16]]
[[4 0 3]
 [2 3 4]]


In [ ]:
a = np.random.randint(1,10,(2,3,4))
print(a)
print(a.shape)
b = np.transpose(a,axes = (1,0,2))      # b[i][j][k] = a[j][i][k]
print(b)
print(b.shape)

[[[4 9 9 5]
  [2 5 8 3]
  [6 3 1 2]]

 [[3 4 5 7]
  [3 3 1 4]
  [5 2 9 7]]]
(2, 3, 4)
[[[4 9 9 5]
  [3 4 5 7]]

 [[2 5 8 3]
  [3 3 1 4]]

 [[6 3 1 2]
  [5 2 9 7]]]
(3, 2, 4)


## 18.随机数组

生成一个 5×5 的随机浮点数矩阵（0~1）。

In [99]:
a = np.random.rand(5,5)
print(a)

[[0.61406156 0.50113429 0.79035376 0.50787575 0.09354608]
 [0.97557759 0.25247165 0.34251344 0.4980313  0.11207677]
 [0.17911359 0.63172091 0.10019047 0.96391497 0.64616882]
 [0.97196847 0.21022639 0.53339349 0.52468716 0.52232257]
 [0.83843451 0.56071206 0.84105767 0.50807446 0.41279506]]


## 19.argmax

找出数组中最大值的索引。

In [110]:
a = np.random.randint(1,20,(6,6))
print(a)
index = np.argwhere(a==6)
print(index)
index2 = np.unravel_index(np.argmax(a), a.shape)

print(index2)
m = np.argmax(a)
print(m)

[[ 4 18 12 13  4 13]
 [10 17  2 10 16 17]
 [15  4  6  4  8  9]
 [ 7  1  9 12 14  9]
 [19 18  5  4  1  1]
 [ 4  1  5 16  2 10]]
[[2 2]]
(4, 0)
24


## 20.综合题（稍微难一点）

给定数组：

[3, 7, 2, 9, 12, 5, 18, 1]

要求：

找出所有大于平均值的数
并按从大到小排序

In [92]:
import numpy as np
a = np.array([3,7,2,9,18,5,12,1])
m = (a>np.average(a))
b = a[m]
print(np.sort(b))

[ 9 12 18]
