1. A
2. B
3. B
4. B
5. B

In [5]:
import numpy as np

A = np.random.randn(3,3)
print(A)
B = A.T
print(B)
C = A @ B
print(C)

D = C.T
print(D)

def duichen(C, D):
    flag = 0
    for i in range(0,3):
        for j in range(0,3):
            if C[i][j]!=D[i][j] :
                flag = 1
                break
    
    return flag

result = duichen(C, D)
if result == 0:
    print('对称')
else:
    print('不对称')

[[ 0.17072651  0.48905897  1.35465035]
 [-1.69994777 -0.96789546 -1.3458903 ]
 [-0.09586461 -1.0060393   0.12478752]]
[[ 0.17072651 -1.69994777 -0.09586461]
 [ 0.48905897 -0.96789546 -1.0060393 ]
 [ 1.35465035 -1.3458903   0.12478752]]
[[ 2.10340378 -2.58679487 -0.33933572]
 [-2.58679487  5.63806473  0.96875538]
 [-0.33933572  0.96875538  1.03687701]]
[[ 2.10340378 -2.58679487 -0.33933572]
 [-2.58679487  5.63806473  0.96875538]
 [-0.33933572  0.96875538  1.03687701]]
对称
